# Generated by Django 4.0.5 on 2022-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_seller_alter_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerid',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
