# Generated by Django 4.0.5 on 2022-07-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_soldproduct_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='cid',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
